// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKYZe5SG0iD_efHOv5WZjLnahJfJm-SFQ',
    appId: '1:360691140061:android:2a5012e50244c904cd2234',
    messagingSenderId: '360691140061',
    projectId: 'fir-push-notify-74835',
    databaseURL: 'https://fir-push-notify-74835-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-push-notify-74835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArzDcPSj2nUPLcHssrd82GBYiRkL50o4c',
    appId: '1:360691140061:ios:f4d187407681baa4cd2234',
    messagingSenderId: '360691140061',
    projectId: 'fir-push-notify-74835',
    databaseURL: 'https://fir-push-notify-74835-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-push-notify-74835.appspot.com',
    iosClientId: '360691140061-7hkkd65osggsenr2qf78fn21ngt995h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyFlutter',
  );
}
